version: "3"
services:
  server:
    build: .
    ports:
      - "8883:5000"
    volumes:
      - .:/app/Server
    environment:
      FLASK_DEBUG: "true"
    depends_on:
      - mysql
  mysql:
    restart: always
    image: zhonghl003/mysql-server:5.7.34-37 # you should modify this (mysql:5.7)
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Serverdb
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: